/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpd.controle_almoxerifado.controle;

import bpd.ultilitarios.ConectaBanco;
import bpd.ultilitarios.InOut;
import bpd.ultilitarios.LookAndFeel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcos.junior
 */
public class SaidaEstoque extends javax.swing.JDialog {
    ConectaBanco con = new ConectaBanco();
    ResultSet rs;
    String NomeBanco="bpd_estoque";
    DateFormat formata = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form EntradaEstoque
     */
    public SaidaEstoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesquisa = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbnOutros = new javax.swing.JRadioButton();
        rbnUniforme = new javax.swing.JRadioButton();
        rbnPapelaria = new javax.swing.JRadioButton();
        txtID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInsumo = new javax.swing.JTextField();
        txtQuantidadeInicial = new javax.swing.JTextField();
        txtRetirada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRetirante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dtRetirada = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saida de Insumo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        tbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Insumo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPesquisa);
        tbPesquisa.getColumnModel().getColumn(0).setResizable(false);
        tbPesquisa.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbPesquisa.getColumnModel().getColumn(1).setResizable(false);
        tbPesquisa.getColumnModel().getColumn(1).setPreferredWidth(260);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/find24.png"))); // NOI18N
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisa)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPesquisa, txtPesquisa});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero do Produto"));

        buttonGroup1.add(rbnOutros);
        rbnOutros.setText("Limpeza / Alimentícios");

        buttonGroup1.add(rbnUniforme);
        rbnUniforme.setText("Uniformes");

        buttonGroup1.add(rbnPapelaria);
        rbnPapelaria.setText("Papelaria");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rbnPapelaria)
                .addGap(10, 10, 10)
                .addComponent(rbnUniforme)
                .addGap(18, 18, 18)
                .addComponent(rbnOutros)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbnPapelaria)
                .addComponent(rbnUniforme)
                .addComponent(rbnOutros))
        );

        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Insumo :");

        jLabel3.setText("Quantidade Atual:");

        jLabel4.setText("Quantidade Retirada:");

        txtInsumo.setEditable(false);

        txtQuantidadeInicial.setEditable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/accept24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Retirante :");

        jLabel5.setText("Data de Retirada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInsumo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRetirante, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtQuantidadeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dtRetirada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(96, 96, 96)
                                    .addComponent(jButton1))))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidadeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRetirante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(dtRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        if(!"".equals(txtPesquisa.getText().trim())){
            if(rbnPapelaria.isSelected()){
                try {
                    PesquisaPapelaria();
                } catch (SQLException ex) {
                    InOut.MsgDeErro(NomeBanco, ex.getMessage());
                }
            }else if(rbnUniforme.isSelected()){
                try {
                    PesquisaUniforme();
                } catch (SQLException ex) {
                    InOut.MsgDeErro(NomeBanco, ex.getMessage());
                }
            }else if(rbnOutros.isSelected()){
                try {
                    PesquisaOutros();
                } catch (SQLException ex) {
                    InOut.MsgDeErro(NomeBanco, ex.getMessage());
                }
            }else{
                InOut.MsgDeAviso(null, "Selecione a Opção de Insumo.");
            }
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void tbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesquisaMouseClicked
        if(rbnPapelaria.isSelected()){
            try {
                PopulaPapelaria();
            } catch (SQLException ex) {
                InOut.MsgDeErro(NomeBanco, ex.getMessage());
            }
        }else if(rbnUniforme.isSelected()){
            try {
                PopulaUniforme();
            } catch (SQLException ex) {
                InOut.MsgDeErro(NomeBanco, ex.getMessage());
            }
        }else if(rbnOutros.isSelected()){
            try {
                PopulaOutros();
            } catch (SQLException ex) {
                InOut.MsgDeErro(NomeBanco, ex.getMessage());
            }
        }else{
            InOut.MsgDeAviso(null, "Selecione a Opção de Insumo.");
        }
    }//GEN-LAST:event_tbPesquisaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if((!"".equals(txtRetirada.getText().trim()))&&(!"".equals(txtQuantidadeInicial.getText().trim()))){
            if(rbnPapelaria.isSelected()){
                try {
                    AtualizaPapelaria();
                    InOut.MsgDeInformacao(null, "Dados Atualizados");
                    LimparDados();
                } catch (SQLException ex) {
                    InOut.MsgDeErro(NomeBanco, ex.getMessage());
                }
            }else if(rbnUniforme.isSelected()){
                try {
                    AtualizaUniforme();
                    InOut.MsgDeInformacao(null, "Dados Atualizados");
                    LimparDados();
                } catch (SQLException ex) {
                    InOut.MsgDeErro(NomeBanco, ex.getMessage());
                }
            }else if(rbnOutros.isSelected()){
                try {
                    AtualizaOutros();
                    InOut.MsgDeInformacao(null, "Dados Atualizados");
                    LimparDados();
                } catch (SQLException ex) {
                    InOut.MsgDeErro(NomeBanco, ex.getMessage());
                }
            }else{
                InOut.MsgDeAviso(null, "Selecione a Opção de Insumo.");
            }
       } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LookAndFeel.McWin();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaidaEstoque dialog = new SaidaEstoque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dtRetirada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbnOutros;
    private javax.swing.JRadioButton rbnPapelaria;
    private javax.swing.JRadioButton rbnUniforme;
    private javax.swing.JTable tbPesquisa;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtInsumo;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtQuantidadeInicial;
    private javax.swing.JTextField txtRetirada;
    private javax.swing.JTextField txtRetirante;
    // End of variables declaration//GEN-END:variables

    private void PesquisaPapelaria() throws SQLException {
        String sql="select idpapelaria,insumo from papelaria where insumo like'%"+txtPesquisa.getText().trim()+"%' order by insumo;";
        DefaultTableModel modelo1 = (DefaultTableModel) tbPesquisa.getModel();
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        modelo1.setRowCount(0);
        while(rs.next()){
            
            modelo1.addRow(new Object[]{
                          rs.getString("idpapelaria"),
                          rs.getString("insumo")
            });
        }
        con.desconecta();
    }
    private void PesquisaUniforme() throws SQLException {
        String sql="select * from uniforme where modelo like'%"+txtPesquisa.getText().trim()+"%' order by modelo,cor_predominante,sexo,tamanho;";
        DefaultTableModel modelo1 = (DefaultTableModel) tbPesquisa.getModel();
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        modelo1.setRowCount(0);
        while(rs.next()){
            
            modelo1.addRow(new Object[]{
                          rs.getString("iduniforme"),
                          rs.getString("modelo")+"-"+rs.getString("cor_predominante")+"-"+rs.getString("sexo")+"-"+rs.getString("tamanho")
            });
        }
        con.desconecta();
    }
    private void PesquisaOutros() throws SQLException {
        String sql="select idalmoxerifado,insumo from almoxerifado where insumo like'%"+txtPesquisa.getText().trim()+"%' order by insumo;";
        DefaultTableModel modelo1 = (DefaultTableModel) tbPesquisa.getModel();
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        modelo1.setRowCount(0);
        while(rs.next()){
            
            modelo1.addRow(new Object[]{
                          rs.getString("idalmoxerifado"),
                          rs.getString("insumo")
            });
        }
        con.desconecta();
    }
    private void PopulaPapelaria() throws SQLException {
        int linha;
        linha=tbPesquisa.getSelectedRow();
        String pesquisa = tbPesquisa.getValueAt(linha, 0).toString();
        String sql="select * from papelaria where idpapelaria='"+pesquisa+"';";
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        while(rs.next()){
            txtID.setText(rs.getString("idpapelaria"));
            txtInsumo.setText(rs.getString("insumo"));
            txtQuantidadeInicial.setText(rs.getString("quantidade"));
        }
        con.desconecta();
    }

    private void PopulaUniforme() throws SQLException {
        int linha;
        linha=tbPesquisa.getSelectedRow();
        String pesquisa = tbPesquisa.getValueAt(linha, 0).toString();
        String sql="select * from uniforme where iduniforme='"+pesquisa+"';";
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        while(rs.next()){
            txtID.setText(rs.getString("iduniforme"));
            txtInsumo.setText(rs.getString("modelo")+"-"+rs.getString("cor_predominante")+"-"+rs.getString("sexo")+"-"+rs.getString("tamanho"));
            txtQuantidadeInicial.setText(rs.getString("quantidade"));
        }
        con.desconecta();
    }

    private void PopulaOutros() throws SQLException {
        int linha;
        linha=tbPesquisa.getSelectedRow();
        String pesquisa = tbPesquisa.getValueAt(linha, 0).toString();
        String sql="select * from almoxerifado where idalmoxerifado='"+pesquisa+"';";
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        while(rs.next()){
            txtID.setText(rs.getString("idalmoxerifado"));
            txtInsumo.setText(rs.getString("insumo"));
            txtQuantidadeInicial.setText(rs.getString("quantidade"));
        }
        con.desconecta();
    }

    private void AtualizaPapelaria() throws SQLException {
        boolean autorizado=ModuloAutoriza();
        if(autorizado){
            int quantidade=ModuloCalculo();
            String sql="update papelaria set "
                    + "quantidade='"+quantidade+"' "
                    + "where idpapelaria='"+txtID.getText().trim()+"';";
            con.conecta(NomeBanco);
            con.executa(sql);
            con.desconecta();
            GravarRelatorio("Papelaria");
        }else{
            InOut.MsgDeErro(null, "Operação não autorizada!\nQuantidade insuficiente em estoque.");
        }
    }

    private void AtualizaUniforme() throws SQLException {
        boolean autorizado=ModuloAutoriza();
        if(autorizado){
            int quantidade=ModuloCalculo();
            String sql="update uniforme set "
                    + "quantidade='"+quantidade+"' "
                    + "where iduniforme='"+txtID.getText().trim()+"';";
            con.conecta(NomeBanco);
            con.executa(sql);
            con.desconecta();
            GravarRelatorio("Uniforme");
        }else{
            InOut.MsgDeErro(null, "Operação não autorizada!\nQuantidade insuficiente em estoque.");
        }
    }

    private void AtualizaOutros() throws SQLException {
        boolean autorizado=ModuloAutoriza();
        if(autorizado){
            int quantidade=ModuloCalculo();
            String sql="update almoxerifado set "
                    + "quantidade='"+quantidade+"' "
                    + "where idalmoxerifado='"+txtID.getText().trim()+"';";
            con.conecta(NomeBanco);
            con.executa(sql);
            con.desconecta();
            GravarRelatorio("Almoxerifado");
        }else{
            InOut.MsgDeErro(null, "Operação não autorizada!\nQuantidade insuficiente em estoque.");
        }
    }

    private int ModuloCalculo() {
        
        int inicial = Integer.parseInt(txtQuantidadeInicial.getText().trim());
        int entrada = Integer.parseInt(txtRetirada.getText().trim());
        int Final = inicial-entrada;
        return Final;  
    }

    private void LimparDados() {
        txtID.setText("");
        txtRetirada.setText("");
        txtInsumo.setText("");    
        txtQuantidadeInicial.setText("");
    }

    private boolean ModuloAutoriza() {
       boolean verifica=true;
       int inicial = Integer.parseInt(txtQuantidadeInicial.getText().trim());
       int entrada = Integer.parseInt(txtRetirada.getText().trim());
       if(inicial<entrada){
           verifica=false;
       }
       return verifica;
    }

    private void GravarRelatorio(String Descricao) {
        String DataRetirada=formata.format(dtRetirada.getDate());
        String sql="insert into retiradas(insumo,descricao,data_retirada,quantidade,funcionario) values ('"
                + ""+txtInsumo.getText().trim()+"','"
                + ""+Descricao+"','"
                + ""+DataRetirada+"','"
                + ""+txtRetirada.getText().trim()+"','"
                + ""+txtRetirante.getText()+"')";

        con.conecta(NomeBanco);
        try {
            con.executa(sql);
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
    }
}
