/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpd.controle_almoxerifado.cadastro;

import bpd.ultilitarios.ConectaBanco;
import bpd.ultilitarios.InOut;
import bpd.ultilitarios.LookAndFeel;
import bpd.ultilitarios.relatorios;
import java.awt.FileDialog;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author marcos.junior
 */
public class Cadastro_Cartao_Intelcav extends javax.swing.JDialog {
    FileDialog fdSelecionar,fdSelecionar2,fdExportarCSV;
    ConectaBanco con = new ConectaBanco();
    ResultSet rs;
    DateFormat formata = new SimpleDateFormat("yyyy-MM-dd");
    String NomeBanco="bpd_estoque";
    String SQL;
    /**
     * Creates new form Cadastro_Cartao_Intelcav
     */
    public Cadastro_Cartao_Intelcav(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        btnPrint.setEnabled(false);
        btnExportar.setEnabled(false);
        fdSelecionar = new FileDialog(this,"Carregar Arquivo", FileDialog.LOAD);
        fdSelecionar2 = new FileDialog(this,"Carregar Arquivo", FileDialog.LOAD);
        fdExportarCSV = new FileDialog(this,"Exportar Arquivo", FileDialog.SAVE);
        CarregarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        txtCodigo = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        txtAP = new javax.swing.JTextField();
        txtPedido = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        dtPedido = new com.toedter.calendar.JDateChooser();
        dtEntrega = new com.toedter.calendar.JDateChooser();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        txtArquivo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JSpinner();
        cbClienteCadastro = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtArte = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbData = new javax.swing.JRadioButton();
        rbAP = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        rbPedido = new javax.swing.JRadioButton();
        txtPesquisa = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        cbCliente = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesquisaCartao = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cartões - INTELCAV");
        setResizable(false);

        label1.setText("Cliente");

        label2.setText("Codigo");

        label3.setText("Nº AP");

        label4.setText("Nº Pedido");

        label5.setText("Data Pedido");

        label6.setText("Data Entrega");

        label7.setText("Quantidade Inicial");

        label8.setText("Arquivo");

        txtArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtArquivoMouseClicked(evt);
            }
        });
        txtArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArquivoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/addfile24.png"))); // NOI18N
        jButton1.setText("Novo");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/accept24.png"))); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/adduser24.png"))); // NOI18N
        jButton4.setText("Novo Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Arte");

        txtArte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtArteMouseClicked(evt);
            }
        });
        txtArte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArquivo))
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidade))
                            .addComponent(dtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAP, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(cbClienteCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(dtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtPedido)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txtArte)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbClienteCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtArte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de Cartão", jPanel1);

        buttonGroup1.add(rbData);
        rbData.setText("Data do Pedido");

        buttonGroup1.add(rbAP);
        rbAP.setText("Nº AP");

        buttonGroup1.add(rbCodigo);
        rbCodigo.setText("Codigo");

        buttonGroup1.add(rbPedido);
        rbPedido.setText("Nº Pedido");

        label9.setText("Cliente");

        tbPesquisaCartao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nº AP", "Cliente", "Codigo", "Data Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPesquisaCartao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbPesquisaCartao);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/find24.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/foldermove24.png"))); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/printer24.png"))); // NOI18N
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(rbData)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbAP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbPedido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPesquisa))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPesquisar)
                                .addComponent(btnExportar)))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbData)
                    .addComponent(rbAP)
                    .addComponent(rbCodigo)
                    .addComponent(rbPedido)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pesquisar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArquivoActionPerformed
        
    }//GEN-LAST:event_txtArquivoActionPerformed

    private void txtArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArquivoMouseClicked
        fdSelecionar.setVisible(true);
        if(fdSelecionar.getFile()==null){
            //txtArquivo.setText("");
        }else{
            txtArquivo.setText(fdSelecionar.getDirectory()+fdSelecionar.getFile());
        }
    }//GEN-LAST:event_txtArquivoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SalvarPedido();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       Pesquisar();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        fdExportarCSV.setVisible(true);
        if(fdExportarCSV.getFile()!=null){
           ExportarCSV();
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Cadastro_Cliente_Intelcav abrir = new Cadastro_Cliente_Intelcav(null, true);
        abrir.setVisible(true);
        CarregarClientes();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtArteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArteMouseClicked
       fdSelecionar2.setVisible(true);
        if(fdSelecionar2.getFile()==null){
           // txtArte.setText("");
        }else{
            txtArte.setText(fdSelecionar2.getDirectory()+fdSelecionar2.getFile());
        }
    }//GEN-LAST:event_txtArteMouseClicked

    private void txtArteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        GerarRelatorio();
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LookAndFeel.McWin();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro_Cartao_Intelcav dialog = new Cadastro_Cartao_Intelcav(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbClienteCadastro;
    private com.toedter.calendar.JDateChooser dtEntrega;
    private com.toedter.calendar.JDateChooser dtPedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JRadioButton rbAP;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbData;
    private javax.swing.JRadioButton rbPedido;
    private javax.swing.JTable tbPesquisaCartao;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtArquivo;
    private javax.swing.JTextField txtArte;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JSpinner txtQuantidade;
    // End of variables declaration//GEN-END:variables

    private void SalvarPedido() {
        String Cliente =cbClienteCadastro.getSelectedItem().toString() ;
        String Codigo  =txtCodigo.getText().trim();
        String NumAP   =txtAP.getText().trim() ;
        String NumPedido=txtPedido.getText().trim();
        String DataPedido=formata.format(dtPedido.getDate());
        String DataEntrega=formata.format(dtEntrega.getDate());
        String Quantidade=txtQuantidade.getValue().toString();
        String Arte=txtArquivo.getText().trim().replace("\\", "/");
        String ArquivoAP=txtArte.getText().trim().replace("\\", "/");
        
        String sSql ;
        sSql = "insert into pedidos_intelcav (cliente ,"
                       +"codigo ,"
                       +"num_ap ,"
                       +"num_pedido ,"
                       +"data_pedido ,"
                       + "data_entrega ,"
                       +"quantidade ,"
                       +"arte,arquivo_ap ) values('"+Cliente+"','"
                                                    +Codigo+"','"
                                                    +NumAP+"','"
                                                    +NumPedido+"','"
                                                    +DataPedido+"','"
                                                    +DataEntrega+"','"
                                                    +Quantidade+"','"
                                                    +Arte+"','"
                                                    +ArquivoAP+"');"
                ;
        
            
            con.conecta(NomeBanco);
            try {
                con.executa(sSql);
                InOut.MsgDeInformacao(null, "Dados Salvos com \nSUCESSO!");
            } catch (SQLException ex) {
                InOut.MsgDeErro(null, ex.getMessage());
            }    
            con.desconecta();
    }

    private void CarregarClientes() {
        
        cbCliente.removeAllItems();
        cbClienteCadastro.removeAllItems();
        
        String sql ="select * from clientes_intelcav order by clientes";
        
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs=con.resultset;
        try {
            while(rs.next()){
                  cbCliente.addItem(rs.getString("clientes"));
                  cbClienteCadastro.addItem(rs.getString("clientes"));
                  
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        con.desconecta();
    }

    private void Pesquisar() {
        String sSql ;
        SQL=new String();
        DefaultTableModel modelo1 = (DefaultTableModel) tbPesquisaCartao.getModel();
        
        if(rbCodigo.isSelected()){
           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and codigo like '"+txtPesquisa.getText()+"%'"; 
        }else if (rbAP.isSelected()){
           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and num_ap like '"+txtPesquisa.getText()+"%'"; 
        }else if (rbData.isSelected()){
           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and data_pedido like '"+txtPesquisa.getText()+"%'";  
        }else if (rbPedido.isSelected()){
           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and num_pedido like '"+txtPesquisa.getText()+"%'"; 
        }else{
            InOut.MsgDeAviso(null,"SELECIONE A OPÇÃO DE PESQUISA" );
            return;
        }
        
        con.conecta(NomeBanco);
        con.executaSelect(sSql);
        rs=con.resultset;
        try {
            modelo1.setRowCount(0);
            while (rs.next()) {
                    modelo1.addRow(new Object[]{
                                
                                rs.getString("num_ap"),
                                rs.getString("cliente"),
                                rs.getString("codigo"),
                                rs.getString("data_pedido"),

                                
                               });
                }
            tbPesquisaCartao.setModel(modelo1);
            btnPrint.setEnabled(true);
            btnExportar.setEnabled(true);
            SQL=sSql;
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
    con.desconecta();   
    }

    private void ExportarCSV() {
//        String sSql = new String();
        StringBuilder imprimir = new StringBuilder();
        
        con = new ConectaBanco();
//        if(rbCodigo.isSelected()){
//           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and codigo like '"+txtPesquisa.getText()+"%'"; 
//        }else if (rbAP.isSelected()){
//           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and num_ap like '"+txtPesquisa.getText()+"%'"; 
//        }else if (rbData.isSelected()){
//           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and data_pedido like '"+txtPesquisa.getText()+"%'";  
//        }else if (rbPedido.isSelected()){
//           sSql = "select * from pedidos_intelcav where cliente='"+cbCliente.getSelectedItem()+"' and num_pedido like '"+txtPesquisa.getText()+"%'"; 
//        }else{
//            InOut.MsgDeAviso(null,"SELECIONE A OPÇÃO DE PESQUISA" );
//            return;
//        }
        
//        System.out.println(sSql);
        PrintWriter out;
        try {
            out = new PrintWriter(fdExportarCSV.getDirectory()+fdExportarCSV.getFile()+".csv");
        
        con.conecta(NomeBanco);
        con.executaSelect(SQL);
        rs=con.resultset;
        out.println("Cliente;Codigo;Numero AP;Numero Pedido;Data Pedido;Data Entrega;Quantidade;Valor;Arquivo;");
            while (rs.next()) {
                        imprimir = new StringBuilder();
                
                        imprimir.append(rs.getString("cliente")).append(";");
                        imprimir.append(rs.getString("codigo")).append(";");
                        imprimir.append(rs.getString("num_ap")).append(";");
                        imprimir.append(rs.getString("num_pedido")).append(";");
                        imprimir.append(rs.getString("data_pedido")).append(";");
                        imprimir.append(rs.getString("data_entrega")).append(";");
                        imprimir.append(rs.getString("quantidade")).append(";");
                        imprimir.append(rs.getString("valor")).append(";");
                        imprimir.append(rs.getString("arquivo")).append(";");
                        
                        out.println(imprimir.toString());
                }
            InOut.MsgDeInformacao(null, "ARQUIVO SALVO COM SUCESSO!");
        } catch (SQLException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        } catch (FileNotFoundException ex) {
           InOut.MsgDeErro(null, ex.getMessage());
        }
        con.desconecta();
    }

    private void GerarRelatorio() {
        try {
            relatorios.Gerar("Relatorio_pedidos", SQL, NomeBanco);
        } catch (JRException ex) {
            InOut.MsgDeErro(NomeBanco, ex.getMessage());
        }
    }
}
