/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpd.login;

import bpd.controle_almoxerifado.Principal;
import bpd.ultilitarios.ConectaBanco;
import bpd.ultilitarios.InOut;
import bpd.ultilitarios.LookAndFeel;
import bpd.ultilitarios.Parametros;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author marcos.junior
 */
public class Login extends javax.swing.JFrame {
    ConectaBanco con = new ConectaBanco();
    ResultSet lRes ;
    String usuario,senha,sSql,verifica;
    String usuario_sessao = System.getProperty("user.name");
    String nomeBanco="bpd_estoque";
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtUsuario.setText(usuario_sessao);
        txtSenha.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BPD - Login");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/user24.png"))); // NOI18N
        jLabel1.setText("Login:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/userid24.png"))); // NOI18N
        jLabel2.setText("Senha:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/close32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/accept32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/login/LogoBPD.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha)
                            .addComponent(txtUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean verificar = VerificarUsuarioMySQL();
        if(verificar){
//            System.out.println("Conectou "+txtUsuario.getText());
//            InOut.MsgDeInformacao("BEM VINDO", "BEM VINDO "+txtUsuario.getText()+" !");
            AbrirPrincipal();
        }
        else{
            InOut.MsgDeErro("ERRO AO CONECTAR", "USUÁRIO / SENHA NÃO CONFEREM \nTENTE NOVAMENTE");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LookAndFeel.Aluminium();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private boolean VerificarUsuario() {
        usuario=new String();
        senha = new String();
        sSql = new String();
        verifica = new String();
        String usu,sen,func ;

        usu = new String();
        sen=new String();
        func=new String();
        
        usuario = txtUsuario.getText();
        senha = txtSenha.getText();
        
        sSql = "select * from funcionario where login='"+usuario+"' ;";
        con.conecta(nomeBanco);
        con.executaSelect(sSql);
        lRes = con.resultset;    
        try {                
            while(lRes.next()){
                usu = lRes.getString("login");
                sen = lRes.getString("senha");
                func = lRes.getString("id_cargo");
            } 
            if(sen.equals(senha)){
                verifica="1";
                Parametros.setsFuncao(func.trim());
                Parametros.setsNmUsuas(usu.trim());
                Parametros.setsSenhaUsuas(sen.trim());
            }else{
                verifica="0";
            }
        } catch (SQLException ex) {
            verifica="0";   
        }
        con.desconecta();
        
        if("0".equals(verifica)){
           return false;
        }else{
            return true;
        }
    }
    private boolean VerificarUsuarioMySQL() {
        usuario=new String();
        senha = new String();
        sSql = new String();
        verifica = new String();
        String usu,sen,func ;

        usu = new String();
        sen=new String();
        func=new String();
        
        usuario = txtUsuario.getText();
        senha = txtSenha.getText();
        
        sSql = "select * from funcionario where login='"+usuario+"' ;";
      
        con.conecta(nomeBanco);
        con.executaSelect(sSql);
        lRes = con.resultset;    
        try {                
            while(lRes.next()){
                usu = lRes.getString("login");
                sen = lRes.getString("senha");
                func = lRes.getString("funcao");              
            } 
            if(sen.equals(senha)){
                verifica="1";
                Parametros.setsFuncao(func.trim());
                Parametros.setsNmUsuas(usu.trim());
                Parametros.setsSenhaUsuas(sen.trim());
            }else{
                verifica="0";
            }
        } catch (SQLException ex) {
            verifica="0";   
        }
        con.desconecta();
        
        if("0".equals(verifica)){
           return false;
        }else{
            return true;
        }
    }
    private void AbrirPrincipal() {
       Principal principal = new Principal();
       principal.setVisible(true);
       this.dispose();
    }

}
