/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpd.controle_almoxerifado;

import bpd.ultilitarios.ConectaBanco;
import bpd.ultilitarios.Configuracao_PC;
import bpd.ultilitarios.InOut;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author marcos.junior
 */
public class AvisoAlmoxerifado extends javax.swing.JDialog {
    ConectaBanco con=new ConectaBanco();
    ResultSet rs;
    String NomeBanco="bpd_estoque";
    /**
     * Creates new form AvisoAlmoxerifado
     */
    public AvisoAlmoxerifado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();  
        Dimension d = tk.getScreenSize();  
//        System.out.println("Screen width = " + d.width);  
//        System.out.println("Screen height = " + d.height);
        this.setLocation(d.width-500, d.height-800);
        CarregarAlerta();
        Relogio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOutros = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUniforme = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPapelaria = new javax.swing.JTable();
        txtRelogio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Alerta de estoque baixo");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Almoxerifado"));

        tbOutros.setForeground(new java.awt.Color(255, 0, 0));
        tbOutros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID ", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbOutros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbOutros);
        tbOutros.getColumnModel().getColumn(0).setResizable(false);
        tbOutros.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbOutros.getColumnModel().getColumn(1).setResizable(false);
        tbOutros.getColumnModel().getColumn(1).setPreferredWidth(250);
        tbOutros.getColumnModel().getColumn(2).setResizable(false);
        tbOutros.getColumnModel().getColumn(2).setPreferredWidth(20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Uniforme"));

        tbUniforme.setForeground(new java.awt.Color(255, 0, 0));
        tbUniforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID ", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUniforme.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbUniforme);
        tbUniforme.getColumnModel().getColumn(0).setResizable(false);
        tbUniforme.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbUniforme.getColumnModel().getColumn(1).setResizable(false);
        tbUniforme.getColumnModel().getColumn(1).setPreferredWidth(250);
        tbUniforme.getColumnModel().getColumn(2).setResizable(false);
        tbUniforme.getColumnModel().getColumn(2).setPreferredWidth(20);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Papelaria"));

        tbPapelaria.setForeground(new java.awt.Color(255, 0, 0));
        tbPapelaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID ", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPapelaria.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbPapelaria);
        tbPapelaria.getColumnModel().getColumn(0).setResizable(false);
        tbPapelaria.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbPapelaria.getColumnModel().getColumn(1).setResizable(false);
        tbPapelaria.getColumnModel().getColumn(1).setPreferredWidth(250);
        tbPapelaria.getColumnModel().getColumn(2).setResizable(false);
        tbPapelaria.getColumnModel().getColumn(2).setPreferredWidth(20);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtRelogio.setText("jLabel1");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/imagens/refresh32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRelogio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtRelogio)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            PopulaTabelaAlmoxerifado();
            PopulaTabelaPapelaria();
            PopulaTabelaUniforme();
        } catch (SQLException ex) {
            InOut.MsgDeErro(NomeBanco, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvisoAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvisoAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvisoAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvisoAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AvisoAlmoxerifado dialog = new AvisoAlmoxerifado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbOutros;
    private javax.swing.JTable tbPapelaria;
    private javax.swing.JTable tbUniforme;
    private javax.swing.JLabel txtRelogio;
    // End of variables declaration//GEN-END:variables

    private void CarregarAlerta() {
        SwingWorker work = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {
                int contador=0;
                int segundos=120;
                int constante=1000;
                while(true){
                    PopulaTabelaAlmoxerifado();
                    PopulaTabelaPapelaria();
                    PopulaTabelaUniforme();
                    System.out.println(contador);
                    contador++;
                    Thread.sleep(segundos*constante);
                }
            }
        };
        work.execute();
    }

    private void PopulaTabelaUniforme() throws SQLException {
        String sql="select * from uniforme where quantidade<=3;";
        DefaultTableModel modelo = (DefaultTableModel) tbUniforme.getModel();
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        modelo.setRowCount(0);
        while(rs.next()){
            modelo.addRow(new Object[]{
                          rs.getString("iduniforme"),
                          rs.getString("modelo")+" "+rs.getString("cor_predominante")+" "+rs.getString("sexo")+" "+rs.getString("tamanho"),
                          rs.getString("quantidade")
            });
        }
        con.desconecta(); 
    }

    private void PopulaTabelaAlmoxerifado() throws SQLException {
        String sql="select * from almoxerifado where quantidade<=5;";
        DefaultTableModel modelo = (DefaultTableModel) tbOutros.getModel();
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        modelo.setRowCount(0);
        while(rs.next()){
            modelo.addRow(new Object[]{
                          rs.getString("idalmoxerifado"),
                          rs.getString("insumo"),
                          rs.getString("quantidade")
            });
        }
        con.desconecta();
    }

    private void PopulaTabelaPapelaria() throws SQLException {
       String sql="select * from papelaria where quantidade<=5;";
        DefaultTableModel modelo = (DefaultTableModel) tbPapelaria.getModel();
        con.conecta(NomeBanco);
        con.executaSelect(sql);
        rs = con.resultset;
        modelo.setRowCount(0);
        while(rs.next()){
            modelo.addRow(new Object[]{
                          rs.getString("idpapelaria"),
                          rs.getString("insumo"),
                          rs.getString("quantidade")
            });
        }
        con.desconecta();
    }

    private void Relogio() {
       SwingWorker relogio = new SwingWorker() {

           @Override
           protected Object doInBackground() throws Exception {
               while(true){
                   txtRelogio.setText(Configuracao_PC.Relogio());
               }
           }
       };
       relogio.execute();
    }
}
