/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpd.controle_almoxerifado;

import bpd.controle_almoxerifado.cadastro.CadastroFornecedor;
import bpd.controle_almoxerifado.cadastro.Cadastro_Cartao_Intelcav;
import bpd.controle_almoxerifado.cadastro.Cadastro_Cliente_Intelcav;
import bpd.controle_almoxerifado.compras.Cadastro_de_Compras;
import bpd.controle_almoxerifado.controle.CadastroEstoque;
import bpd.controle_almoxerifado.controle.EntradaEstoque;
import bpd.controle_almoxerifado.controle.ImportarDados;
import bpd.controle_almoxerifado.controle.Pesquisa_Pedidos_Intelcav;
import bpd.controle_almoxerifado.controle.RelatorioRetiradas;
import bpd.controle_almoxerifado.controle.SaidaEstoque;
import bpd.controle_almoxerifado.producao.CadastroCartao;
import bpd.controle_almoxerifado.producao.MostrarRelatorioEstoque;
import bpd.controle_almoxerifado.producao.MovimentoEstoque;
import bpd.controle_almoxerifado.ti.CadastroRamais;
import bpd.controle_almoxerifado.ti.RelacaoCargos;
import bpd.login.Login;
import bpd.ultilitarios.Configuracao_PC;
import bpd.ultilitarios.InOut;
import bpd.ultilitarios.Parametros;
import bpd.ultilitarios.relatorios;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author marcos.junior
 */
public class Principal extends javax.swing.JFrame {
    
    public String funcao = Parametros.getsFuncao();
    public String usuario = Parametros.getsNmUsuas();
    public String senha = Parametros.getsSenhaUsuas();
    String Banco1="bpd_estoque";

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        CarregarPermissoes();
        CarragaDadosLocais();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomePC = new javax.swing.JLabel();
        txtIPPC = new javax.swing.JLabel();
        txtOS = new javax.swing.JLabel();
        txtJavaVersao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mAdm = new javax.swing.JMenu();
        mIntelcav = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        mCadastroFornecedor = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        mRelatorio = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mEstoque = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mEstoqueEntrada = new javax.swing.JMenuItem();
        mProd = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        mTI = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BPD - Controle de Estoque");
        setResizable(false);

        txtUsuario.setText("jLabel2");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bpd/login/LogoBPD.png"))); // NOI18N

        txtNomePC.setText("jLabel3");

        txtIPPC.setText("jLabel3");

        txtOS.setText("jLabel4");

        txtJavaVersao.setText("jLabel5");

        jMenu1.setText("Arquivo");

        jMenuItem5.setText("Desconectar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Sair");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        mAdm.setText("Administrativo");

        mIntelcav.setText("Intelcav");

        jMenuItem1.setText("Cadastro de Cartão -  Pedido Intelcav");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mIntelcav.add(jMenuItem1);

        jMenuItem14.setText("Importar Dados");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mIntelcav.add(jMenuItem14);

        mAdm.add(mIntelcav);

        mCadastroFornecedor.setText("Cadastro Fornecedor");
        mCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroFornecedorActionPerformed(evt);
            }
        });
        mAdm.add(mCadastroFornecedor);

        jMenuItem7.setText("Cadastro de Mercadorias");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mAdm.add(jMenuItem7);

        jMenuItem15.setText("Cadastro de Compras");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        mAdm.add(jMenuItem15);

        mRelatorio.setText("Relatórios");

        jMenuItem8.setText("Papelaria");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mRelatorio.add(jMenuItem8);

        jMenuItem9.setText("Uniformes");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mRelatorio.add(jMenuItem9);

        jMenuItem10.setText("Alimentício / Limpeza");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mRelatorio.add(jMenuItem10);

        jMenuItem11.setText("Retiradas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mRelatorio.add(jMenuItem11);

        mAdm.add(mRelatorio);

        jMenuBar1.add(mAdm);

        mEstoque.setText("Estoque");

        jMenuItem2.setText("Retirada");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mEstoque.add(jMenuItem2);

        mEstoqueEntrada.setText("Entrada");
        mEstoqueEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEstoqueEntradaActionPerformed(evt);
            }
        });
        mEstoque.add(mEstoqueEntrada);

        jMenuBar1.add(mEstoque);

        mProd.setText("Produção");
        mProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProdActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Cadastro de Cartão - Estoque BPD");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mProd.add(jMenuItem4);

        jMenuItem12.setText("Movimento de Estoque de Cartão");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mProd.add(jMenuItem12);

        jMenuItem13.setText("Relatório de Estoque de Cartão");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mProd.add(jMenuItem13);

        jMenuBar1.add(mProd);

        mTI.setText("TI");

        jMenuItem3.setText("Relação de Usuários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mTI.add(jMenuItem3);

        jMenuItem16.setText("Cadastro de Ramais");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        mTI.add(jMenuItem16);

        jMenuBar1.add(mTI);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIPPC)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtNomePC))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJavaVersao)
                            .addComponent(txtOS))))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario)
                            .addComponent(txtOS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomePC)
                            .addComponent(txtJavaVersao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIPPC)))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProdActionPerformed
        
    }//GEN-LAST:event_mProdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println("clicou");
        Cadastro_Cartao_Intelcav cadastroCartao = new Cadastro_Cartao_Intelcav(this, false);
        cadastroCartao.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        RelacaoCargos abrir = new RelacaoCargos(this, true);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroFornecedorActionPerformed
        CadastroFornecedor abrir = new CadastroFornecedor(this, true);
        abrir.setVisible(true);
    }//GEN-LAST:event_mCadastroFornecedorActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            AbrirRelatorioPapelaria();
        } catch (JRException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            AbrirRelatorioUniformes();
        } catch (JRException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CadastroCartao abrir = new  CadastroCartao(this, true);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mEstoqueEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEstoqueEntradaActionPerformed
        EntradaEstoque abrir = new EntradaEstoque(this, true);
        abrir.setVisible(true);
    }//GEN-LAST:event_mEstoqueEntradaActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        RelatorioRetiradas abrir = new RelatorioRetiradas(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            AbrirRelatorioAlmoxerifado();
        } catch (JRException ex) {
            InOut.MsgDeErro(null, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        MovimentoEstoque abrir = new MovimentoEstoque(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        MostrarRelatorioEstoque abrir = new MostrarRelatorioEstoque(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SaidaEstoque abrir  = new SaidaEstoque(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        ImportarDados abrir = new ImportarDados(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Login abrir = new Login();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CadastroEstoque abrir = new CadastroEstoque(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        Cadastro_de_Compras abrir = new Cadastro_de_Compras(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        CadastroRamais abrir = new CadastroRamais(this, false);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed


    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mAdm;
    private javax.swing.JMenuItem mCadastroFornecedor;
    private javax.swing.JMenu mEstoque;
    private javax.swing.JMenuItem mEstoqueEntrada;
    private javax.swing.JMenu mIntelcav;
    private javax.swing.JMenu mProd;
    private javax.swing.JMenu mRelatorio;
    private javax.swing.JMenu mTI;
    private javax.swing.JLabel txtIPPC;
    private javax.swing.JLabel txtJavaVersao;
    private javax.swing.JLabel txtNomePC;
    private javax.swing.JLabel txtOS;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void CarragaDadosLocais() {
        txtUsuario.setText("Usuário: "+usuario);
        txtIPPC.setText("IP: "+ Configuracao_PC.IPPC());
        txtJavaVersao.setText("Versão Java: "+Configuracao_PC.JavaVersao());
        txtNomePC.setText("Nome do computador: "+ Configuracao_PC.NomePC());
        txtOS.setText(Configuracao_PC.NomeOS()+" "+Configuracao_PC.VersaoOS());
        
    }

    private void AbrirRelatorioPapelaria() throws JRException {
        String sql = "Select * from papelaria order by fornecedor,insumo;";
        relatorios.Gerar("Papelaria", sql, Banco1);
    }

    private void AbrirRelatorioUniformes() throws JRException {
        String sql = "Select * from uniforme group by sexo,fornecedor,modelo,cor_predominante,tamanho,iduniforme;";
        relatorios.Gerar("Uniformes", sql, Banco1);
    }

    private void AbrirRelatorioAlmoxerifado() throws JRException {
        String sql = "Select * from almoxerifado order by insumo;";
        relatorios.Gerar("Almoxerifado", sql, Banco1);
    }

    private void CarregarPermissoes() {
        switch (Integer.parseInt(funcao)){
            case 1:
                mAdm.setEnabled(true);
                mCadastroFornecedor.setEnabled(true);
                mEstoque.setEnabled(true);
                mEstoqueEntrada.setEnabled(true);
                mIntelcav.setEnabled(true);
                mProd.setEnabled(true);
                mRelatorio.setEnabled(true);
                mTI.setEnabled(true);
                break;
            case 2:
                mAdm.setEnabled(true);
                mCadastroFornecedor.setEnabled(true);
                mEstoque.setEnabled(true);
                mEstoqueEntrada.setEnabled(true);
                mIntelcav.setEnabled(true);
                mProd.setEnabled(true);
                mRelatorio.setEnabled(true);
                mTI.setEnabled(true);
                break;
            case 3:
                mAdm.setEnabled(true);
                mCadastroFornecedor.setEnabled(true);
                mEstoque.setEnabled(true);
                mEstoqueEntrada.setEnabled(true);
                mIntelcav.setEnabled(true);
                mProd.setEnabled(false);
                mRelatorio.setEnabled(true);
                mTI.setEnabled(false);
                AvisoAlmoxerifado abrir = new  AvisoAlmoxerifado(this, false);
                abrir.setVisible(true);
                break;
            case 4:
                mAdm.setEnabled(false);
                mCadastroFornecedor.setEnabled(false);
                mEstoque.setEnabled(false);
                mEstoqueEntrada.setEnabled(true);
                mIntelcav.setEnabled(false);
                mProd.setEnabled(true);
                mRelatorio.setEnabled(false);
                mTI.setEnabled(false);
                break;
        }
    }
}
